### PR TITLE
add Rapid.Space ORS and SlapOS

### PR DESCRIPTION
**Pull request by frequent**

### CODE REVIEW

**Comment by mychele** [comment]
Thanks for the PR! I took some time to take a look at the Rapid.Space website but I am still not sure what this is about. Is it a hardware project? With a closed-source RAN software? Would you mind telling us more about this?

Thank you!

**Comment by frequent** [comment]
@mychele : sorry, missed your post. Answers:
> Is it a hardware project? With a closed-source RAN software? Would you mind telling us more about this?

It is an open source hardware project which is compatible with
* closed source SDR ([Amarisoft](https://www.amarisoft.com/))
* open source OSS/BSS ([SlapOS](https://slapos.nexedi.com/))

and could become compatible one day with open source SDR (ex. SRS, OAI) if one does the effort to port it to that open source hardware. Hope that answers your questions.

**Comment by mychele** [comment]
Thanks, got it. Interesting projects!
However, I would not put the ORS in the software components. Can you keep SlapOS in this PR and open another one for ORS under the SDR platforms? I think that in our taxonomy it's the closest category.

**Comment by frequent** [comment]
@mychele - removed Rapid.Space ORS here.

**Review by mychele — APPROVED** [review]
@leonardobonati all good on my side, can we merge?
@frequent thanks for the PR

**Pull request merged**
